[build]
builder = "dockerfile"
dockerfilePatch = "./Acme.CargoExpress.API/Dockerfile"

[deploy]
startCommand = "./Acme.CargoExpress.API"
restartPolicyType = "always"
healthCheckPath = "/health"